Repository handley-lab/anesthetic, pull requests merged in 2020-05, with the labels that each got.

#80 automatic minmax limits
  README.rst
  anesthetic/samples.py
  tests/example_data/pc.ranges
  tests/test_samples.py
Labels: enhancement

#85 -infinity handling in set_beta
  anesthetic/samples.py
  tests/test_samples.py
Labels: bug

#87 Convert numpy to np
  anesthetic/boundary.py
  anesthetic/gui/plot.py
  anesthetic/kde.py
  anesthetic/plot.py
  anesthetic/read/getdistreader.py
  anesthetic/read/montepythonreader.py
  anesthetic/read/multinestreader.py
  anesthetic/read/polychordreader.py
  anesthetic/samples.py
  anesthetic/utils.py
  anesthetic/weighted_pandas.py
  bin/gen_data.py
  bin/plot.py
  images/animate.py
  tests/test_plot.py
  tests/test_samples.py
  tests/test_utils.py
  tests/test_weighted_pandas.py
Labels: enhancement

#75 Version 1.3
  README.rst
Labels: versionbump
