Repository handley-lab/anesthetic, pull requests merged in 2023-08, with the labels that each got.

#319 Test suite tidy
  README.rst
  anesthetic/_version.py
  anesthetic/convert.py
  anesthetic/plot.py
  anesthetic/read/ultranest.py
  bin/bump_version.py
  bin/check_version.py
  bin/utils.py
  tests/test_convert.py
  tests/test_gui.py
  tests/test_plot.py
  tests/test_reader.py
  tests/test_samples.py
  tests/utils.py
Labels: tests

#331 Fix failing docs
  README.rst
  anesthetic/_version.py
  pyproject.toml
Labels: bug, documentation

#330 Automatic bin computation for weighted data
  README.rst
  anesthetic/_version.py
  anesthetic/plot.py
  anesthetic/plotting/_matplotlib/hist.py
  anesthetic/utils.py
  pyproject.toml
  tests/test_plot.py
Labels: enhancement
