Repository handley-lab/anesthetic, pull requests merged in 2023-02, with the labels that each got.

#258 `MCMCSamples` methods for burn-in removal and Gelman--Rubin statistic
  .github/workflows/CI.yml
  anesthetic/read/chain.py
  anesthetic/read/cobaya.py
  anesthetic/read/getdist.py
  anesthetic/read/utils.py
  anesthetic/samples.py
  anesthetic/weighted_pandas.py
  bin/run_tests
  tests/example_data/cb.1.txt
  tests/example_data/cb.2.txt
  tests/example_data/cb.input.yaml
  tests/example_data/cb.updated.yaml
  tests/example_data/cb_single_chain.updated.yaml
  tests/test_reader.py
  tests/test_samples.py
  tests/test_weighted_pandas.py
Labels: enhancement

#263 matplotlib 3.7.0 moved SubplotBase
  README.rst
  anesthetic/_version.py
  anesthetic/gui/plot.py
  tests/test_plot.py
Labels: bug

#243 Update documentation for 2.0 release
  .github/workflows/CI.yaml
  .readthedocs.yml
  README.rst
  anesthetic/__init__.py
  anesthetic/_version.py
  anesthetic/boundary.py
  anesthetic/convert.py
  anesthetic/examples/perfect_ns.py
  anesthetic/examples/utils.py
  anesthetic/gui/plot.py
  anesthetic/gui/widgets.py
  anesthetic/kde.py
  anesthetic/labelled_pandas.py
  anesthetic/plot.py
  anesthetic/plotting/__init__.py
  anesthetic/plotting/_core.py
  anesthetic/plotting/_matplotlib/core.py
  anesthetic/plotting/_matplotlib/hist.py
  anesthetic/read/chain.py
  anesthetic/read/cobaya.py
  anesthetic/read/getdist.py
  anesthetic/read/multinest.py
  anesthetic/read/polychord.py
  anesthetic/samples.py
  anesthetic/scripts.py
  anesthetic/utils.py
  anesthetic/weighted_pandas.py
  demo.ipynb
  demo.py
  docs/requirements.txt
  docs/source/anesthetic.examples.rst
  docs/source/anesthetic.gui.rst
  docs/source/anesthetic.plotting.rst
  docs/source/anesthetic.read.rst
  docs/source/anesthetic.rst
  docs/source/conf.py
  docs/source/index.rst
  docs/source/modules.rst
  docs/source/plotting.rst
  docs/source/quickstart.rst
  docs/source/reading_writing.rst
  docs/source/samples.rst
  docs/templates/package.rst_t
  docs/templates/toc.rst_t
  tests/test_samples.py
Labels: documentation
